# Generated by Django 3.1.14 on 2024-04-18 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0002_propertypluginmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='your_models', to=settings.AUTH_USER_MODEL),
        ),
    ]
